const { MongoClient } = require('mongodb');

const NEIGHBORHOODS = [
  'ALEJANDRIA 1', 'ALEJANDRIA 3', 'ALEJANDRIA 4', 'ALEJANDRIA 5', 'ALEJANDRIA 6',
  'ALEJANDRIA 7', 'ALEJANDRIA 8', 'ALEJANDRÍA REAL', 'ALICANTE', 'ALTOS DE GUALI',
  'ALTOS DE GUALI 1', 'ALTOS DE GUALI 3', 'ALTOS DE GUALI 5', 'ALTOS DE SAN JUAN',
  'ARBOLEDA', 'AURORA', 'BACATA', 'BALCONES DE FUNZA', 'BELLIZCA',
  'CAMPIÑAS DE SAN GABRIEL', 'CAMPIÑAS DEL SOL', 'CENTRO FUNZA', 'CENTRO MOSQUERA',
  'CIUDAD DE LOS PUERTOS', 'CIUDAD SABANA', 'COLIBRI', 'CONDOMINIO PALO ALTO',
  'CONJUNTO CELTA', 'CONJUNTO RESIDENCIAL PETREL', 'CORTIJO DE SERREZUELA',
  'EL BREMEN', 'EL CABRERO', 'EL DIAMANTE', 'EL HATO', 'EL PALMAR', 'EL POBLADO',
  'EL REMANSO', 'EL TRÉBOL', 'ESTANCIA 2', 'FUNZA CENTRO', 'HACIENDA ALCALA',
  'HACIENDA EL ROSAL', 'HACIENDA LOS CABALLOS', 'HACIENDA SAN ANDRES',
  'HALCONES DE MOSQUERA', 'IREGUI', 'IREGUI 2', 'LA ARBOLEDA', 'LA AURORA',
  'LA CABAÑA', 'LA CAMPIÑA', 'LA CARTUJA', 'LA CITA', 'LA CUMBRE',
  'LA ESPERANZA', 'LA ESTANCIA', 'LA FORTUNA', 'LA PROSPERIDAD, MADRID',
  'LOS PUERTOS', 'LOS VIRREYES', 'MADRID', 'MAIPORE', 'MALLORCA', 'MALLORCA 2',
  'MALLORCA 3', 'MARTINEZ RICO', 'MAYORCA 3', 'MEXICO', 'NOVATERRA CEDRO',
  'NOVATERRA CAOBA', 'NOVATERRA CEREZO', 'NOVATERRA GUAYACÁN', 'NOVATERRA ROBLE',
  'NOVATERRA CANELO', 'NOVATERRA ZAPÁN', 'NOVATERRA NOGAL', 'NOVATERRA CIPRÉS',
  'NOVAERRA ARRAYÁN', 'NUEVA CASTILLA', 'NUEVA GERONA', 'OASIS DE FUNZA',
  'PARQUES DE SAN ISIDRO', 'PETREL', 'PLANADAS', 'POBLADO', 'PORTALES DE FUNZA',
  'PORTON DE MALLORCA', 'PORVENIR CENTRO', 'PORVENIR RIO', 'PRADERAS I',
  'PRADOS DE SAN ANDRÉS', 'PROVIVIENDA', 'PUERTO ALEGRE', 'PUERTO AZUL',
  'PUERTO PLATA', 'PUERTO VALLARTA', 'QUINTAS DE CELTA', 'QUINTAS DEL TREBOL',
  'RECODOS DE MOSQUERA', 'REMANSO', 'RESERVA DE MALLORCA', 'RESERVA DE MALLORCA 3',
  'RESERVA DE USCA', 'RESERVA DE MALLORCA 2', 'RESERVAS DE USCA',
  'RINCON DE VIRREYES', 'SAMARKANDA', 'SAN ISIDRIO', 'SAN ISIDRO', 'SAN MARCOS',
  'SAN MIGUEL', 'SAN SEBASTIAN', 'SAN TELMO', 'SANTA ANA', 'SANTA TERESITA',
  'SANTANA', 'SANTELMO', 'SENDEROS DE FUNZA', 'SENDEROS DE SIETE TROJES',
  'SERENAS', 'SERREZUELITA', 'SIETE TROJES', 'SOCIEGO', 'TREBOL DEL GUALI',
  'TREBOL DEL GUALI 2', 'VELVERDE', 'VERONES', 'VILLA DEL ROCIO', 'VILLA DEL SOL',
  'VILLA DIANA', 'VILLA IMPERIAL', 'VILLA JENNY', 'VILLA MARCELA', 'VILLA MARIA',
  'VILLA MARIA 2', 'VILLA MARIA 3', 'VILLA MARIA 4', 'VILLA MARY', 'VILLA NUEVA',
  'VILLA PAOLA', 'VILLA SAJONIA', 'VILLA YENNY', 'VILLANUEVA', 'VILLAS',
  'VILLAS DEL TREBOL', 'VILLASAJONIA', 'VIRREYES', 'WAYRA', 'ZUAME', 'ZUAME 2',
];

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/MCI-APP-db';
  const client = new MongoClient(uri);

  try {
    await client.connect();
    const db = client.db();
    const collection = db.collection('neighborhoods');

    const docs = NEIGHBORHOODS.map((name) => ({ name }));
    const result = await collection.insertMany(docs, { ordered: false });

    console.log(`✅ Inserted ${Object.keys(result.insertedIds).length} neighborhoods`);
  } catch (error: any) {
    if (error.code === 11000) {
      console.log('ℹ️  Some neighborhoods already exist (duplicates skipped)');
    } else {
      console.error('❌ Error seeding neighborhoods:', error);
    }
  } finally {
    await client.close();
  }
}

seed();
