import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import './i18n'

// Register service worker generated by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register'

registerSW({
  onNeedRefresh() {
    // You can show a toast/modal to prompt user to refresh
  },
  onOfflineReady() {
    // Optional callback
  }
})

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
