export const Neighborhood = [
    { label: 'ALEJANDRIA 1', value: 1 },
    { label: 'ALEJANDRIA 3', value: 2 },
    { label: 'ALEJANDRIA 4', value: 3 },
    { label: 'ALEJANDRIA 5', value: 4 },
    { label: 'ALEJANDRIA 6', value: 5 },
    { label: 'ALEJANDRIA 7', value: 6 },
    { label: 'ALEJANDRIA 8', value: 7 },
    { label: 'ALEJANDRÍA REAL', value: 8 },
    { label: 'ALICANTE', value: 9 },
    { label: 'ALTOS DE GUALI', value: 10 },
    { label: 'ALTOS DE GUALI 1', value: 11 },
    { label: 'ALTOS DE GUALI 3', value: 12 },
    { label: 'ALTOS DE GUALI 5', value: 13 },
    { label: 'ALTOS DE SAN JUAN', value: 14 },
    { label: 'ARBOLEDA', value: 15 },
    { label: 'AURORA', value: 16 },
    { label: 'BACATA', value: 17 },
    { label: 'BALCONES DE FUNZA', value: 18 },
    { label: 'BELLIZCA', value: 19 },
    { label: 'CAMPIÑAS DE SAN GABRIEL', value: 20 },
    { label: 'CAMPIÑAS DEL SOL', value: 21 },
    { label: 'CENTRO FUNZA', value: 22 },
    { label: 'CENTRO MOSQUERA', value: 23 },
    { label: 'CIUDAD DE LOS PUERTOS', value: 24 },
    { label: 'CIUDAD SABANA', value: 25 },
    { label: 'COLIBRI', value: 26 },
    { label: 'CONDOMINIO PALO ALTO', value: 27 },
    { label: 'CONJUNTO CELTA', value: 28 },
    { label: 'CONJUNTO RESIDENCIAL PETREL', value: 29 },
    { label: 'CORTIJO DE SERREZUELA', value: 30 },
    { label: 'EL BREMEN', value: 31 },
    { label: 'EL CABRERO', value: 32 },
    { label: 'EL DIAMANTE', value: 33 },
    { label: 'EL HATO', value: 34 },
    { label: 'EL PALMAR', value: 35 },
    { label: 'EL POBLADO', value: 36 },
    { label: 'EL REMANSO', value: 37 },
    { label: 'EL TRÉBOL', value: 38 },
    { label: 'ESTANCIA 2', value: 39 },
    { label: 'FUNZA CENTRO', value: 40 },
    { label: 'HACIENDA ALCALA', value: 41 },
    { label: 'HACIENDA EL ROSAL', value: 42 },
    { label: 'HACIENDA LOS CABALLOS', value: 43 },
    { label: 'HACIENDA SAN ANDRES', value: 44 },
    { label: 'HALCONES DE MOSQUERA', value: 45 },
    { label: 'IREGUI', value: 46 },
    { label: 'IREGUI 2', value: 47 },
    { label: 'LA ARBOLEDA', value: 48 },
    { label: 'LA AURORA', value: 49 },
    { label: 'LA CABAÑA', value: 50 },
    { label: 'LA CAMPIÑA', value: 51 },
    { label: 'LA CARTUJA', value: 52 },
    { label: 'LA CITA', value: 53 },
    { label: 'LA CUMBRE', value: 54 },
    { label: 'LA ESPERANZA', value: 55 },
    { label: 'LA ESTANCIA', value: 56 },
    { label: 'LA FORTUNA', value: 57 },
    { label: 'LA PROSPERIDAD, MADRID', value: 58 },
    { label: 'LOS PUERTOS', value: 59 },
    { label: 'LOS VIRREYES', value: 60 },
    { label: 'MADRID', value: 61 },
    { label: 'MAIPORE', value: 62 },
    { label: 'MALLORCA', value: 63 },
    { label: 'MALLORCA 2', value: 64 },
    { label: 'MALLORCA 3', value: 65 },
    { label: 'MARTINEZ RICO', value: 66 },
    { label: 'MAYORCA 3', value: 67 },
    { label: 'MEXICO', value: 68 },
    { label: 'NOVATERRA CEDRO', value: 69 },
    { label: 'NOVATERRA CAOBA', value: 70 },
    { label: 'NOVATERRA CEREZO', value: 71 },
    { label: 'NOVATERRA GUAYACÁN', value: 72 },
    { label: 'NOVATERRA ROBLE', value: 73 },
    { label: 'NOVATERRA CANELO', value: 74 },
    { label: 'NOVATERRA ZAPÁN', value: 75 },
    { label: 'NOVATERRA NOGAL', value: 76 },
    { label: 'NOVATERRA CIPRÉS', value: 77 },
    { label: 'NOVAERRA ARRAYÁN', value: 78 },
    { label: 'NUEVA CASTILLA', value: 79 },
    { label: 'NUEVA GERONA', value: 80 },
    { label: 'OASIS DE FUNZA', value: 81 },
    { label: 'PARQUES DE SAN ISIDRO', value: 82 },
    { label: 'PETREL', value: 83 },
    { label: 'PLANADAS', value: 84 },
    { label: 'POBLADO', value: 85 },
    { label: 'PORTALES DE FUNZA', value: 86 },
    { label: 'PORTON DE MALLORCA', value: 87 },
    { label: 'PORVENIR CENTRO', value: 88 },
    { label: 'PORVENIR RIO', value: 89 },
    { label: 'PRADERAS I', value: 90 },
    { label: 'PRADOS DE SAN ANDRÉS', value: 91 },
    { label: 'PROVIVIENDA', value: 92 },
    { label: 'PUERTO ALEGRE', value: 93 },
    { label: 'PUERTO AZUL', value: 94 },
    { label: 'PUERTO PLATA', value: 95 },
    { label: 'PUERTO VALLARTA', value: 96 },
    { label: 'QUINTAS DE CELTA ', value: 97 },
    { label: 'QUINTAS DEL TREBOL', value: 98 },
    { label: 'RECODOS DE MOSQUERA', value: 99 },
    { label: 'REMANSO', value: 100 },
    { label: 'RESERVA DE MALLORCA', value: 101 },
    { label: 'RESERVA DE MALLORCA 3', value: 102 },
    { label: 'RESERVA DE USCA', value: 103 },
    { label: 'RESERVA DE MALLORCA 2', value: 104 },
    { label: 'RESERVAS DE USCA', value: 105 },
    { label: 'RINCON DE VIRREYES', value: 106 },
    { label: 'SAMARKANDA', value: 107 },
    { label: 'SAN ISIDRIO', value: 108 },
    { label: 'SAN ISIDRO', value: 109 },
    { label: 'SAN MARCOS', value: 110 },
    { label: 'SAN MIGUEL', value: 111 },
    { label: 'SAN SEBASTIAN', value: 112 },
    { label: 'SAN TELMO', value: 113 },
    { label: 'SANTA ANA', value: 114 },
    { label: 'SANTA TERESITA', value: 115 },
    { label: 'SANTANA', value: 116 },
    { label: 'SANTELMO', value: 117 },
    { label: 'SENDEROS DE FUNZA', value: 118 },
    { label: 'SENDEROS DE SIETE TROJES', value: 119 },
    { label: 'SERENAS', value: 120 },
    { label: 'SERREZUELITA', value: 121 },
    { label: 'SIETE TROJES', value: 122 },
    { label: 'SOCIEGO', value: 123 },
    { label: 'TREBOL DEL GUALI', value: 124 },
    { label: 'TREBOL DEL GUALI 2', value: 125 },
    { label: 'VELVERDE', value: 126 },
    { label: 'VERONES', value: 127 },
    { label: 'VILLA DEL ROCIO', value: 128 },
    { label: 'VILLA DEL SOL', value: 129 },
    { label: 'VILLA DIANA', value: 130 },
    { label: 'VILLA IMPERIAL', value: 131 },
    { label: 'VILLA JENNY', value: 132 },
    { label: 'VILLA MARCELA', value: 133 },
    { label: 'VILLA MARIA', value: 134 },
    { label: 'VILLA MARIA 2', value: 135 },
    { label: 'VILLA MARIA 3', value: 136 },
    { label: 'VILLA MARIA 4', value: 137 },
    { label: 'VILLA MARY', value: 138 },
    { label: 'VILLA NUEVA', value: 139 },
    { label: 'VILLA PAOLA', value: 140 },
    { label: 'VILLA SAJONIA', value: 141 },
    { label: 'VILLA YENNY', value: 142 },
    { label: 'VILLANUEVA', value: 143 },
    { label: 'VILLAS', value: 144 },
    { label: 'VILLAS DEL TREBOL', value: 145 },
    { label: 'VILLASAJONIA', value: 146 },
    { label: 'VIRREYES', value: 147 },
    { label: 'WAYRA', value: 148 },
    { label: 'ZUAME', value: 149 },
    { label: 'ZUAME 2', value: 150 },
] as const
