export const MCI_LOCATIONS = [
  "Acacias",
  "Arauca",
  "Armenia",
  "Barbosa",
  "Barrancabermeja",
  "Barranquilla",
  "Bello",
  "Bogotá D.C.",
  "Bogotá - Ciudad Bolivar",
  "Bogotá - Usme",
  "Bogotá - Bosa",
  "Bucaramanga",
  "Cali",
  "Campoalegre",
  "Cartagena",
  "Cartagena Centro",
  "Casanare Villa Nueva",
  "Chiquinquirá",
  "Chocontá",
  "Cubarral",
  "Curumaní",
  "Cúcuta",
  "Duitama",
  "El Playón",
  "El Rosal",
  "Envigado",
  "Facatativá",
  "Fusagasugá",
  "Garzón",
  "Girardot",
  "Granada",
  "Ibagué",
  "Ipiales",
  "Itagüí",
  "La Dorada",
  "La Mesa",
  "La Plata",
  "La Vega",
  "Madrid",
  "Magangué",
  "Maicao",
  "Manizales",
  "Medellín",
  "Mesitas del Colegio",
  "Moniquirá",
  "Montería",
  "Mosquera",
  "Málaga",
  "Neiva",
  "Ocaña",
  "Palmira",
  "Pamplona",
  "Pasto",
  "Pereira Norte",
  "Pereira",
  "Pitalito",
  "Popayán",
  "Puerto López",
  "Puerto Salgar",
  "Puerto Wilches",
  "Rionegro",
  "Sabana de Torres",
  "Sabana Norte",
  "Sabaneta",
  "San Gil",
  "San Juan de Río Seco",
  "Santa Marta",
  "Sibaté",
  "Sincelejo",
  "Soacha",
  "Socorro",
  "Sogamoso",
  "Soledad",
  "Tame",
  "Tauramena",
  "Tenjo",
  "Tunja",
  "Valledupar",
  "Villa del Rosario",
  "Villa de San Diego de Ubaté",
  "Villavicencio",
  "Vélez",
  "Yondó",
  "Yopal",
  "Zipaquirá",
] as const;

export type MCILocation = (typeof MCI_LOCATIONS)[number];
